# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-exp',
                'doc_host': 'https://uphill-ai.github.io',
                'git_url': 'https://github.com/uphill-ai/python-exp',
                'lib_path': 'python_exp'},
  'syms': {'python_exp.core': {'python_exp.core.foo': ('core.html#foo', 'python_exp/core.py')}}}
